[package]
name = "pine-lexer"
version.workspace = true
edition = "2021"
description = "Lexer for Pine Script."
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
eyre = { workspace = true }
pine-core = { workspace = true }
thiserror = { workspace = true }
