[package]
name = "pine-lang"
version.workspace = true
edition = "2021"
description = "A Pine Script compiler, interpreter, and backtesting engine in Rust."
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
pine-core = { workspace = true }
pine-data = { workspace = true }
pine-ast = { workspace = true }
pine-lexer = { workspace = true }
pine-parser = { workspace = true }
pine-interpreter = { workspace = true }
pine-builtins = { workspace = true }
pine-broker = { workspace = true }
pine-sema = { workspace = true }
pine-diagnostics = { workspace = true }
eyre = { workspace = true }
