[package]
name = "pine-integration-tests"
version.workspace = true
edition = "2021"
publish = false

[[test]]
name = "integration"
path = "integration.rs"

[[test]]
name = "corpus"
path = "corpus.rs"

[dependencies]
pine-lang.workspace = true
pine-interpreter.workspace = true
pine-lexer.workspace = true
pine-parser.workspace = true
pine-ast.workspace = true
pine-core.workspace = true
pine-data.workspace = true
eyre.workspace = true
walkdir = "2"
