[package]
name = "pine-interpreter"
version.workspace = true
edition = "2021"
description = "Interpreter and runtime for Pine Script."
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
pine-ast = { workspace = true }
pine-broker = { workspace = true }
pine-core = { workspace = true }
pine-parser = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
eyre = { workspace = true }
