[package]
name = "pine-sema"
version.workspace = true
edition = "2021"
description = "Semantic analysis for Pine Script."
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
pine-ast = { workspace = true }
pine-core = { workspace = true }
pine-diagnostics = { workspace = true }
pine-interpreter = { workspace = true }
pine-parser = { workspace = true }

[dev-dependencies]
pine-lexer = { workspace = true }
