//@version=5
indicator("types/udt_copy")
// Test UDT copy method
type pivotPoint
    int x
    float y

pivot1 = pivotPoint.new()
pivot1.x := 1000
pivot1.y := 50.5

pivot2 = pivotPoint.copy(pivot1)
pivot2.x := 2000

x1 = pivot1.x
x2 = pivot2.x
y1 = pivot1.y
y2 = pivot2.y

log.info(str.tostring(x1))
log.info(str.tostring(x2))
log.info(str.tostring(y1))
log.info(str.tostring(y2))

// Expected output:
// 1000
// 2000
// 50.5
// 50.5
