[package]
name = "pine-builtins"
version.workspace = true
edition = "2021"
description = "Built-in functions and namespaces for the Pine Script interpreter."
license.workspace = true

[dependencies]
pine-builtin-macro = { workspace = true }
pine-ast = { workspace = true }
pine-core = { workspace = true }
pine-broker = { workspace = true }
pine-interpreter = { workspace = true }
chrono = { workspace = true }
