[package]
name = "pine-builtin-macro"
version.workspace = true
edition = "2021"
description = "Derive macro for defining Pine Script builtin functions."
license.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
