[package]
name = "pine-lsp"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Language server for Pine Script."
publish = false

[dependencies]
pine-lang = { workspace = true }
tower-lsp-server = "0.22"
tokio = { version = "1", features = ["rt-multi-thread", "io-std", "macros"] }
